approval_policy = "never"
sandbox_mode = "danger-full-access"
personality = "pragmatic"

[projects."/home/hlavo/workspace"]
trust_level = "trusted"

[shell_environment_policy]
inherit = "core"
include_only = ["PATH","HOME","USER","SHELL","LANG","LC_ALL","TERM",
                "CONDA_PREFIX","CONDA_DEFAULT_ENV","VIRTUAL_ENV"]

[shell_environment_policy.set]
PATH = "/home/hlavo/workspace/dev/venv-docker/bin:/home/hlavo/miniconda3/envs/hlavo/bin:/home/hlavo/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
